#!/usr/bin/env bash

# Configure Nginx to have a custom 404 page that contains the string given

# Update package lists
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a default index page
echo "Hello World" | sudo tee /var/www/html/index.html > /dev/null

# Configure redirection
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure the custom 404 page
sudo sed -i '/server_name _;/a \ \terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

