#!/usr/bin/env bash
# Installs and setup haproxy

# apt-get install --no-install-recommends software-properties-common
# add-apt-repository ppa:vbernat/haproxy-2.0
# apt-get install haproxy=2.0.\*

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

echo "
frontend frontend_http
    bind *:80
    mode http
    default_backend backend_http

backend backend_http
    mode http
    balance roundrobin
    server 194232-web-01 100.25.192.12:80 check
    server 194232-web-02 100.25.22.89:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy service
sudo sed -i 's/#ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo service haproxy start

# verify HAProxy configuration
# wait for HAProxy to start
sleep 5
curl -Is localhost | grep "Server:\|X-Served-By:"

# restart HAProxy LB to apply changes
sudo service haproxy restart
