#!/usr/bin/env bash
#Bash script that configures a server to on port 0
sudo rm /etc/ngnix/sites-enabled/default
ln -s etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service ngnix restart
