#!/usr/bin/env bash
# debugging nginx (service (init) must say that nginx is not running)
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
