#!/usr/bin/env bash
# Fix by installing apache and changing output to hello holberton
apt-get install apache2 -y
service apache2 start
echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
echo "ServerName localhost" | sudo tee -a /etc/apache2/apache2.conf
