#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.

sudo service nginx stop
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default

chmod +rw /etc/nginx/nginx.conf
for pid in $(pidof apache2); do
    sudo kill "$pid"
done
sudo -u nginx service nginx start
